version: "3.8"
services:
  spring_boot_db_migration_app:
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    depends_on:
      - mysqldb
    restart: on-failure:3

  mysqldb:
    image: mysql:8
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: db_migration
      MYSQL_ROOT_PASSWORD: root

volumes:
  db-data: